version: "3"
services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll/
      - ./vendor/bundle:/usr/local/bundle
    working_dir: /srv/jekyll
    command: sh -c 'foreman start'
    ports:
      - "8080:8080"

